{"name": "test_registration_form", "status": "failed", "statusDetails": {"message": "AssertionError: The message in the alert box does not match the expected", "trace": "self = <tests.test_registration.TestRegistrationForm object at 0x000002358A7BF340>, browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a7fe4256cedaaa947d33a12af12a196a\")>\n\n    @pytest.mark.registration_test(scope='function', autouse=True)\n    def test_registration_form(self, browser):\n        page = RegistrationPage(browser, 'https://www.demoblaze.com/')\n        page.open_page()\n        page.registration_new_user()\n>       page.is_alert_message_present(RegistrationData.sing_up_successful_message)\n\ntests\\test_registration.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.registration_page.RegistrationPage object at 0x000002358A7BF4C0>, allert_message = 'Sign up successful.'\n\n    def is_alert_message_present(self, allert_message):\n        '''Функция проверки появления алерта с соответствующим сообщением'''\n        with allure.step('Проверяем, что появился алерт с соответствующим сообщением'):\n    \n            try:\n                WebDriverWait(self.browser, timeout=1).until(EC.alert_is_present(), 'Timed out waiting.')\n                sign_up_alert = self.browser.switch_to.alert\n>               assert sign_up_alert.text == allert_message, 'The message in the alert box does not match the expected'\nE               AssertionError: The message in the alert box does not match the expected\n\npages\\base_page.py:41: AssertionError"}, "steps": [{"name": "Открываем главную страницу", "status": "passed", "start": 1689791841038, "stop": 1689791841956}, {"name": "Нажаимаем на кнопку регистрации                          нового пользователя в navbar.", "status": "passed", "start": 1689791841956, "stop": 1689791841987}, {"name": "Заполняем поля username и password.", "status": "passed", "start": 1689791841987, "stop": 1689791842287}, {"name": "Нажимаем на кнопку регистрации                          нового пользователя в модальном окне регистрации.", "status": "passed", "start": 1689791842287, "stop": 1689791842311}, {"name": "Проверяем, что появился алерт с соответствующим сообщением", "status": "failed", "statusDetails": {"message": "AssertionError: The message in the alert box does not match the expected\n", "trace": "  File \"C:\\dev\\UI-test-automation\\pages\\base_page.py\", line 41, in is_alert_message_present\n    assert sign_up_alert.text == allert_message, 'The message in the alert box does not match the expected'\n"}, "start": 1689791842311, "stop": 1689791842816}], "start": 1689791841037, "stop": 1689791842816, "uuid": "eba2391f-6063-4260-a61a-1b5cead5a439", "historyId": "7c62ead2c384f2f63a2e5d8cf54b42d8", "testCaseId": "7c62ead2c384f2f63a2e5d8cf54b42d8", "fullName": "tests.test_registration.TestRegistrationForm#test_registration_form", "labels": [{"name": "tag", "value": "registration_test(scope='function', autouse=True)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_registration"}, {"name": "subSuite", "value": "TestRegistrationForm"}, {"name": "host", "value": "DESKTOP-QIGAR15"}, {"name": "thread", "value": "16860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_registration"}]}